const fs = require("node:fs/promises");
const path = require("node:path");
const esbuild = require("esbuild");

const root = path.resolve(__dirname, "..");
const codeMirrorSharedPackages = [
  "@codemirror/language",
  "@codemirror/state",
  "@codemirror/view"
];

function codeMirrorGlobalShimPlugin(packages) {
  const packageSet = new Set(packages);
  return {
    name: "codemirror-global-shim",
    setup(build) {
      build.onResolve({ filter: /^@codemirror\/(?:language|state|view)$/ }, (args) => {
        if (!packageSet.has(args.path)) {
          return undefined;
        }

        return {
          path: args.path,
          namespace: "codemirror-global-shim"
        };
      });

      build.onLoad({ filter: /.*/, namespace: "codemirror-global-shim" }, async (args) => {
        const imported = await import(args.path);
        const exportLines = Object.keys(imported)
          .filter((name) => name !== "default" && /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name))
          .sort()
          .map((name) => `export const ${name} = sharedModule[${JSON.stringify(name)}];`);
        const defaultLine = Object.prototype.hasOwnProperty.call(imported, "default")
          ? "\nexport default sharedModule.default;"
          : "";

        return {
          contents: [
            `const sharedModule = globalThis.EditorWorkbenchCodeMirror && globalThis.EditorWorkbenchCodeMirror.modules && globalThis.EditorWorkbenchCodeMirror.modules[${JSON.stringify(args.path)}];`,
            `if (!sharedModule) { throw new Error(${JSON.stringify(args.path + " runtime is not available.")}); }`,
            exportLines.join("\n") + defaultLine
          ].join("\n"),
          loader: "js"
        };
      });
    }
  };
}

async function buildBundle(entryPoint, outfile, globalName, options = {}) {
  await fs.mkdir(path.dirname(outfile), { recursive: true });
  await esbuild.build({
    entryPoints: [entryPoint],
    outfile,
    bundle: true,
    format: "iife",
    globalName,
    platform: "browser",
    target: "es2020",
    legalComments: "linked",
    sourcemap: false,
    minify: false,
    loader: options.loader || {},
    plugins: options.plugins || [],
    banner: {
      js: "/* Local runtime bundle generated by npm run build:libs. Do not load from a CDN at runtime. */"
    }
  });
}

async function buildCodeMirrorLanguageBundle(entryPoint, outfile, globalName) {
  await buildBundle(entryPoint, outfile, globalName, {
    plugins: [codeMirrorGlobalShimPlugin(codeMirrorSharedPackages)]
  });
}

async function main() {
  await buildBundle(
    path.join(root, "tools", "bundle-src", "editor-bundle.js"),
    path.join(root, "editor-workbench", "libs", "codemirror", "editor.bundle.js"),
    "EditorWorkbenchCodeMirrorBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "sanitize-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "shared", "sanitize", "sanitize.bundle.js"),
    "EditorWorkbenchSanitizeBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "markdown-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "markdown", "runtime", "markdown.bundle.js"),
    "EditorWorkbenchMarkdownBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-markdown-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "markdown", "runtime", "codemirror-markdown.bundle.js"),
    "EditorWorkbenchCodeMirrorMarkdownBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "mermaid-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "mermaid", "runtime", "mermaid.bundle.js"),
    "EditorWorkbenchMermaidBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "graphviz-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "graphviz", "runtime", "graphviz.bundle.js"),
    "EditorWorkbenchGraphvizBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-dot-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "graphviz", "runtime", "codemirror-dot.bundle.js"),
    "EditorWorkbenchCodeMirrorDotBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-html-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "svg", "runtime", "codemirror-html.bundle.js"),
    "EditorWorkbenchCodeMirrorHtmlBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-json-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "json", "runtime", "codemirror-json.bundle.js"),
    "EditorWorkbenchCodeMirrorJsonBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-xml-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "xml", "runtime", "codemirror-xml.bundle.js"),
    "EditorWorkbenchCodeMirrorXmlBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "yaml-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "yaml", "runtime", "yaml.bundle.js"),
    "EditorWorkbenchYamlBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-yaml-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "yaml", "runtime", "codemirror-yaml.bundle.js"),
    "EditorWorkbenchCodeMirrorYamlBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-javascript-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "javascript", "runtime", "codemirror-javascript.bundle.js"),
    "EditorWorkbenchCodeMirrorJavaScriptBundle"
  );

  await buildCodeMirrorLanguageBundle(
    path.join(root, "tools", "bundle-src", "codemirror-python-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "python", "runtime", "codemirror-python.bundle.js"),
    "EditorWorkbenchCodeMirrorPythonBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "prettier-javascript-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "javascript", "runtime", "prettier-javascript.bundle.js"),
    "EditorWorkbenchPrettierJavaScriptBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "prettier-xml-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "xml", "runtime", "prettier-xml.bundle.js"),
    "EditorWorkbenchPrettierXmlBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "csv-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "csv", "runtime", "csv.bundle.js"),
    "EditorWorkbenchCsvBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "ruff-python-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "python", "runtime", "ruff-python.bundle.js"),
    "EditorWorkbenchRuffPythonBundle",
    {
      loader: {
        ".wasm": "binary"
      }
    }
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "jsmind-bundle.js"),
    path.join(root, "editor-workbench", "plugins", "jsmind", "runtime", "jsmind.bundle.js"),
    "EditorWorkbenchJsMindBundle"
  );

  await fs.mkdir(path.join(root, "editor-workbench", "plugins", "jsmind", "runtime"), { recursive: true });
  await fs.copyFile(
    path.join(root, "node_modules", "jsmind", "style", "jsmind.css"),
    path.join(root, "editor-workbench", "plugins", "jsmind", "runtime", "jsmind.css")
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
