const fs = require("node:fs/promises");
const path = require("node:path");
const esbuild = require("esbuild");

const root = path.resolve(__dirname, "..");

async function buildBundle(entryPoint, outfile, globalName) {
  await fs.mkdir(path.dirname(outfile), { recursive: true });
  await esbuild.build({
    entryPoints: [entryPoint],
    outfile,
    bundle: true,
    format: "iife",
    globalName,
    platform: "browser",
    target: "es2020",
    legalComments: "linked",
    sourcemap: false,
    minify: false,
    banner: {
      js: "/* Local runtime bundle generated by npm run build:libs. Do not load from a CDN at runtime. */"
    }
  });
}

async function main() {
  await buildBundle(
    path.join(root, "tools", "bundle-src", "editor-bundle.js"),
    path.join(root, "editor-workbench", "libs", "codemirror", "editor.bundle.js"),
    "EditorWorkbenchCodeMirrorBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "markdown-bundle.js"),
    path.join(root, "editor-workbench", "libs", "markdown", "markdown.bundle.js"),
    "EditorWorkbenchMarkdownBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "mermaid-bundle.js"),
    path.join(root, "editor-workbench", "libs", "mermaid", "mermaid.bundle.js"),
    "EditorWorkbenchMermaidBundle"
  );

  await buildBundle(
    path.join(root, "tools", "bundle-src", "graphviz-bundle.js"),
    path.join(root, "editor-workbench", "libs", "graphviz", "graphviz.bundle.js"),
    "EditorWorkbenchGraphvizBundle"
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
